language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sivalka/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sivalka/client-test npm test

after_success:
  - docker build -t sivalka/multi-client ./client
  - docker build -t sivalka/multi-nginx ./nginx
  - docker build -t sivalka/multi-server ./server
  - docker build -t sivalka/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #push all images to docker hub
  - docker push sivalka/multi-client
  - docker push sivalka/multi-nginx
  - docker push sivalka/multi-server
  - docker push sivalka/multi-worker
